name: Build and Run C++

on:
  push:
    branches: [main]

  pull_request:
    branches: [dev]

jobs:
  build:
    name: ${{ matrix.name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ============================================================
          # Linux x64 GCC
          # ============================================================

          - name: Linux x64 GCC
            os: ubuntu-24.04
            build_type: Release
            configure_args: >-
              -DCMAKE_CXX_COMPILER=g++


          # ============================================================
          # Linux x64 Clang
          # ============================================================

          - name: Linux x64 Clang
            os: ubuntu-24.04
            build_type: Release
            configure_args: >-
              -DCMAKE_CXX_COMPILER=clang++


          # ============================================================
          # Linux ARM64 GCC
          # ============================================================

          - name: Linux ARM64 GCC
            os: ubuntu-24.04-arm
            build_type: Release
            configure_args: >-
              -DCMAKE_CXX_COMPILER=g++

          # ============================================================
          # Linux ARM64 Clang
          # ============================================================

          - name: Linux ARM64 Clang Default
            os: ubuntu-24.04-arm
            build_type: Release
            configure_args: >-
              -DCMAKE_CXX_COMPILER=clang++

          # ============================================================
          # Windows x64 MSVC
          # ============================================================

          - name: Windows x64 MSVC Default
            os: windows-2025
            build_type: Release
            configure_args: >-
              -G "Visual Studio 18 2026"
              -A x64

          # ============================================================
          # Windows x64 ClangCL
          # ============================================================

          - name: Windows x64 ClangCL Default
            os: windows-2025
            build_type: Release
            configure_args: >-
              -G "Visual Studio 18 2026"
              -A x64
              -T ClangCL

          # ============================================================
          # Mac OS
          # ============================================================
          - name: macOS ARM64 Clang Default
            os: macos-26
            build_type: Release
            configure_args: >-
              -G "Ninja"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          ${{ matrix.configure_args }}

      - name: Build
        run: cmake
          --build build
          --config ${{ matrix.build_type }}

      - name: Run tests
        run: ctest
          --test-dir build
          -C ${{ matrix.build_type }}
          --output-on-failure
          --no-tests=error